services:
  loja-do-valdir:
    build:
      context: .
      dockerfile: src/LojaDoValdir/Dockerfile
    image: loja-valdir:latest
    container_name: loja-do-valdir
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - loja-network

  db:
    image: postgres
    hostname: db # nome fixo do container dentro da rede
    container_name: loja-db
    restart: always # serve para reiniciar automaticamente caso pare
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: loja-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - loja-network

networks:
  loja-network:
    driver: bridge

volumes:
  db-data:
    driver: local