version: '3.4'

services:
  lojadovaldir:
    image: lojadovaldir
    build:
      context: .
      dockerfile: src/LojaDoValdir/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
