name: Main Release Pipeline

# Gatilho: só roda quando houver push ou merge na main
on:
  push:
    branches:
      - main

jobs:
  setup-build: # restaura dependências e compila código.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

  container-test: # cria um container Docker e testa o endpoint de healthcheck
    needs: setup-build  # Só executa se o setup-build passar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Run Docker Container
        run: |
          docker build -t loja-valdir:latest -f src/LojaDoValdir/Dockerfile .
          docker run -d -p 8080:8080 --name loja-valdir loja-valdir:latest
          sleep 10  # Aguarda um tempo para garantir que a aplicação iniciou

      - name: Test Healthcheck Endpoint
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthcheck)
          if [ "$STATUS" -ne 200 ]; then
            echo "Healthcheck failed with status $STATUS"
            exit 1
          fi
          echo "Healthcheck passed with status $STATUS"

      - name: Cleanup
        run: docker stop loja-valdir && docker rm loja-valdir